=== HGeist/xml/schema/schema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- Ein Koordinatenpunkt. optional: address -->
	<xsd:complexType name="point">
                <xsd:attribute name="lon" type="xsd:decimal"/>
                <xsd:attribute name="lat" type="xsd:decimal"/>
                <xsd:attribute name="ele" type="xsd:decimal"/>
		<xsd:sequence>
			<xsd:element name="address" type="address" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Eine Adresse. Optional: alles -->
	<xsd:complexType name="address">
		<xsd:sequence>
			<xsd:element name="street" type="xsd:string" minOccurs="0"/>
			<xsd:element name="streetnumber" type="xsd:string" minOccurs="0"/>
			<xsd:element name="zipcode" type="xsd:string" minOccurs="0"/>
			<xsd:element name="city" type="xsd:string" minOccurs="0"/>
			<xsd:element name="country" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Eine Längenangabe mit Dezimalzahl und Längeneinheit. Default ist Meter (m). -->
        <xsd:complexType name="length">
                <xsd:simpleContent>
                        <xsd:extension base="xsd:decimal">
                                <xsd:attribute name="unit" type="xsd:string" default="m" />
                        </xsd:extension>
                </xsd:simpleContent>
        </xsd:complexType>

        <!-- Qualitätsangabe eines Tracks -->
        <xsd:simpleType name="quality">
                <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                        <xsd:maxInclusive value="5"/>
                </xsd:restriction>
        </xsd:simpleType>
	
	<!-- Track-Element. optional: name, totalLength, description, trackTypes, trackAttributes, trackCharacters, trackRoadbeds, 
	trackRoads, quality, totalAscend, totalDescend, altitudeMax, altitudeMin, altitudeDifference -->
	<xsd:element name="track">
		<xsd:complexType>
                	<xsd:sequence>
                		<xsd:element name="description" type="xsd:string" minOccurs="0"/>
                		<xsd:element name="trackProperty">
                			<xsd:simpleType>
        					<xsd:restriction base="xsd:string">
                					<xsd:enumeration value="Round Trip"/>
                                                        <xsd:enumeration value="One Way Trip"/>
        					</xsd:restriction>
    					</xsd:simpleType>
                		</xsd:element>
                		<xsd:element name="trackTypes" minOccurs="0">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="trackType" type="xsd:string" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                		<xsd:element name="trackAttributes" minOccurs="0">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="trackAttribute" type="xsd:string" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                		<xsd:element name="trackCharacters" minOccurs="0">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="trackCharacter" type="xsd:string" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                		<xsd:element name="trackRoadbeds" minOccurs="0">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="trackRoadbed" type="xsd:string" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                		<xsd:element name="trackRoads" minOccurs="0">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="trackRoad" type="xsd:string" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                		<xsd:element name="points">
                			<xsd:complexType>
                				<xsd:sequence>
                					<xsd:element name="point" type="point" maxOccurs="unbounded"/>
                				</xsd:sequence>
                			</xsd:complexType>
                		</xsd:element>
                	</xsd:sequence>
                        <xsd:attribute name="trackName" type="xsd:string"/>
                        <xsd:attribute name="author" type="xsd:string"/>
                        <xsd:attribute name="totalLength" type="length"/>
                        <xsd:attribute name="totalAscend" type="length"/>
                        <xsd:attribute name="totalDescend" type="length"/>
                        <xsd:attribute name="altitudeMax" type="length"/>
                        <xsd:attribute name="altitudeMin" type="length"/>
                        <xsd:attribute name="altitudeDifference" type="length"/>
                        <xsd:attribute name="quality" type="quality"/>
                        <xsd:attribute name="createTimestamp" type="xsd:dateTime" use="required"/>
                </xsd:complexType>
	</xsd:element>

	<!-- Ein POI. Optional: beginTimestamp, endTimestamp (falls es ein zeitbegrenztes Event ist) -->
	<xsd:element name="pointOfInterest">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="position" type="point"/>
			</xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string"/>
                        <xsd:attribute name="type" type="xsd:string" use="required"/>
                        <xsd:attribute name="beginTimestamp" type="xsd:dateTime"/>
                        <xsd:attribute name="endTimestamp" type="xsd:dateTime"/>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== HGeist/xml/schema/test.xml
<?xml version="1.0"?>
<track xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://cochu.dyndns.org schema.xsd">

  <name>Testtrack</name>
  <length>7834659203</length>
  <createTimestamp>2012-06-11T15:41:52+01:00</createTimestamp>
  <author>Eike Cochu</author>
  <description>This is a test track xml file for validation purposes only.</description>
  <motionType>Motor</motionType>
  <trackType>One Way Trip</trackType>
  <quality>5</quality>
  <points>
  	<point>
  		<lon>52.123566</lon>
  		<lat>8.7526482</lat>
  		<address>
  			<street>Graefenberger Weg</street>
  			<streetnumber>1A</streetnumber>
  			<city>Berlin</city>
  			<zipcode>12205</zipcode>
  			<country>Germany</country>
  		</address>
  	</point>
  	<point>
  		<lon>72.123566</lon>
  		<lat>9.7526482</lat>
  	</point>
  	<point>
  		<lon>12.123566</lon>
  		<lat>23.7545682</lat>
  	</point>
  	<point>
  		<lon>64.122768</lon>
  		<lat>5.7526482</lat>
  	</point>
  	<point>
  		<lon>22.112566</lon>
  		<lat>19.787682</lat>
  	</point>
  </points>

</track>
